# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sw_scan.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1518, 603)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.frame = QtWidgets.QFrame(self.splitter)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.pb_filter = QtWidgets.QPushButton(self.frame)
        self.pb_filter.setGeometry(QtCore.QRect(340, 500, 80, 25))
        self.pb_filter.setObjectName("pb_filter")
        self.widget = QtWidgets.QWidget(self.frame)
        self.widget.setGeometry(QtCore.QRect(11, 11, 232, 58))
        self.widget.setObjectName("widget")
        self.formLayout = QtWidgets.QFormLayout(self.widget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.le_id = QtWidgets.QLineEdit(self.widget)
        self.le_id.setObjectName("le_id")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.le_id)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.le_description = QtWidgets.QLineEdit(self.widget)
        self.le_description.setObjectName("le_description")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.le_description)
        self.tw = QtWidgets.QTableWidget(self.splitter)
        self.tw.setObjectName("tw")
        self.tw.setColumnCount(0)
        self.tw.setRowCount(0)
        self.horizontalLayout.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1518, 22))
        self.menubar.setObjectName("menubar")
        self.menuQuit = QtWidgets.QMenu(self.menubar)
        self.menuQuit.setObjectName("menuQuit")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_quit = QtWidgets.QAction(MainWindow)
        self.action_quit.setObjectName("action_quit")
        self.action_load_file = QtWidgets.QAction(MainWindow)
        self.action_load_file.setObjectName("action_load_file")
        self.menuQuit.addAction(self.action_load_file)
        self.menuQuit.addAction(self.action_quit)
        self.menubar.addAction(self.menuQuit.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pb_filter.setText(_translate("MainWindow", "Filter"))
        self.label.setText(_translate("MainWindow", "ID contains"))
        self.label_2.setText(_translate("MainWindow", "Description contains"))
        self.menuQuit.setTitle(_translate("MainWindow", "SW Scan"))
        self.action_quit.setText(_translate("MainWindow", "Quit"))
        self.action_load_file.setText(_translate("MainWindow", "Load file"))
